version: "3.9"

services:
  postgres15:
    image: postgres:15
    container_name: postgres15
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: hireminator-web
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DATABASE_HOST: postgres15
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - postgres15

volumes:
  pg_data:
